import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className='flex flex-col h-screen justify-center items-center bg-primary-black'>
          <div className='p-1 px-3 w-relative h-relative self-center bg-primary-green rounded-lg'>
              {children}
          </div>
        </main>
      </body>
    </html>
  )
}
