name: Run QA steps

on:
  push:
    branches:
      - main
      - feature/cicd
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: Scan the code with SonarQube and publish results to sonarcloud.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
